name: Build NativeScript Project

on:
  push:
    branches: [ "feature/pipeline" ]
  pull_request:
    branches: [ "feature/pipeline" ]

jobs:

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  ns-android:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Install NativeScript
      run: npm install nativescript

    - name: Build android
      shell: pwsh
      run: ns build android
