name: Build NativeScript Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_PATH: "ZeroWasteFrdige"

jobs:

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  ns-android:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Install NativeScript
      run: npm install -g nativescript

    - name: Build android
      run: ns build android --path ${{ env.PROJECT_PATH }}
